version: "{build}"
environment:
  matrix:
    - job_name: Windows x64
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: Linux x64
      appveyor_build_worker_image: Ubuntu
configuration:
  - Release
install:
  - cmd: cmake -G "Visual Studio 16 2019" .
  - sh: |
      echo "== Installing dependencies ==" && sudo apt -qq update && sudo apt -qq install -y gcc-10 g++-10
      sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-10 30
      sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-10 30
      cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION .
for:
  - matrix:
      only:
        - job_name: Windows x64
    build:
      project: dtasks.sln
      parallel: true
      verbosity: minimal
  - matrix:
      only:
        - job_name: Linux x64
    build_script:
      - sh: echo -e "== Building Linux $CONFIGURATION ==" && cmake --build . -v || exit 1

matrix:
  fast_finish: true

skip_branch_with_pr: true
